create table IF NOT EXISTS zno_stats(
    year smallint,
    outid varchar(36) primary key,
    birth smallint,
    sextypename varchar(15),
    regname varchar(100),
    areaname varchar(100),
    tername varchar(100),
    regtypename varchar(100),
    tertypename varchar(10),
    classprofilename varchar(50),
    classlangname varchar(20),
    eoname varchar(500),
    eotypename varchar(100),
    eoregname varchar(100),
    eoareaname varchar(100),
    eotername varchar(100),
    eoparent varchar(500),

    ukrtest varchar(100),
    ukrteststatus varchar(50),
    ukrball100 real,
    ukrball12 smallint,
    ukrball smallint,
    ukradaptscale smallint,
    ukrptname varchar(500),
    ukrptregname varchar(100),
    ukrptareaname varchar(100),
    ukrpttername varchar(100),

    histtest varchar(100),
    histlang varchar(50),
    histteststatus varchar(50),
    histball100 real,
    histball12 smallint,
    histball smallint,
    histptname varchar(500),
    histptregname varchar(100),
    histptareaname varchar(100),
    histpttername varchar(100),

    mathtest varchar(100),
    mathlang varchar(50),
    mathteststatus varchar(50),
    mathball100 real,
    mathball12 smallint,
    mathball smallint,
    mathptname varchar(500),
    mathptregname varchar(100),
    mathptareaname varchar(100),
    mathpttername varchar(100),

    phystest varchar(100),
    physlang varchar(50),
    physteststatus varchar(50),
    physball100 real,
    physball12 smallint,
    physball smallint,
    physptname varchar(500),
    physptregname varchar(100),
    physptareaname varchar(100),
    physpttername varchar(100),

    chemtest varchar(100),
    chemlang varchar(50),
    chemteststatus varchar(50),
    chemball100 real,
    chemball12 smallint,
    chemball smallint,
    chemptname varchar(500),
    chemptregname varchar(100),
    chemptareaname varchar(100),
    chempttername varchar(100),

    biotest varchar(100),
    biolang varchar(50),
    bioteststatus varchar(50),
    bioball100 real,
    bioball12 smallint,
    bioball smallint,
    bioptname varchar(500),
    bioptregname varchar(100),
    bioptareaname varchar(100),
    biopttername varchar(100),

    geotest varchar(100),
    geolang varchar(50),
    geoteststatus varchar(50),
    geoball100 real,
    geoball12 smallint,
    geoball smallint,
    geoptname varchar(500),
    geoptregname varchar(100),
    geoptareaname varchar(100),
    geopttername varchar(100),

    engtest varchar(100),
    engteststatus varchar(50),
    engball100 real,
    engball12 smallint,
    engdpalevel varchar(50),
    engball smallint,
    engptname varchar(500),
    engptregname varchar(100),
    engptareaname varchar(100),
    engpttername varchar(100),

    fratest varchar(100),
    frateststatus varchar(50),
    fraball100 real,
    fraball12 smallint,
    fradpalevel varchar(50),
    fraball smallint,
    fraptname varchar(500),
    fraptregname varchar(100),
    fraptareaname varchar(100),
    frapttername varchar(100),

    deutest varchar(100),
    deuteststatus varchar(50),
    deuball100 real,
    deuball12 smallint,
    deudpalevel varchar(50),
    deuball smallint,
    deuptname varchar(500),
    deuptregname varchar(100),
    deuptareaname varchar(100),
    deupttername varchar(100),

    spatest varchar(100),
    spateststatus varchar(50),
    spaball100 real,
    spaball12 smallint,
    spadpalevel varchar(50),
    spaball smallint,
    spaptname varchar(500),
    spaptregname varchar(100),
    spaptareaname varchar(100),
    spapttername varchar(100)
)